server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://172.18.58.79:5432/ead-authuser
    username: ead-authuser
    password: ead-authuser
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true