server:
  port: 80

spring:
  datasource:
#    url: jdbc:postgresql://eadauthuser.cau7apdyt9pp.us-east-2.rds.amazonaws.com:5432/eadauthuser
#    username: postgres
#    password: Pr1me1r0Banc0
    url: jdbc:postgresql://172.18.58.79:5432/ead-authuser
    username: ead-authuser
    password: ead-authuser
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: ALWAYS

logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO